import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import Ajv2020 from 'ajv/dist/2020.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const SCHEMA_PATH = path.resolve(__dirname, '../schema/review.schema.json');
let schemaValidator = null;

export function getValidator() {
  if (!schemaValidator) {
    const ajv = new Ajv2020({ allErrors: true });
    const schemaContent = JSON.parse(fs.readFileSync(SCHEMA_PATH, 'utf8'));
    schemaValidator = ajv.compile(schemaContent);
  }
  return schemaValidator;
}

/**
 * Validates a review JSON object or raw string.
 * Enforces schema compliance, head SHA match, and complete flag.
 */
export function validateReview(reviewInput, expectedHeadSha) {
  let review = reviewInput;
  if (typeof reviewInput === 'string') {
    try {
      review = JSON.parse(reviewInput);
    } catch (err) {
      throw new Error(`Malformed review JSON: ${err.message}`);
    }
  }

  if (!review || typeof review !== 'object') {
    throw new Error('Review payload must be a non-null JSON object');
  }

  const validate = getValidator();
  const valid = validate(review);
  if (!valid) {
    const errorDetails = (validate.errors || [])
      .map(e => `${e.instancePath || 'root'} ${e.message}`)
      .join('; ');
    throw new Error(`Review schema validation failed: ${errorDetails}`);
  }

  if (expectedHeadSha && review.head_sha !== expectedHeadSha) {
    throw new Error(
      `Reviewed head_sha mismatch: expected '${expectedHeadSha}', received '${review.head_sha}'`
    );
  }

  if (review.complete !== true) {
    throw new Error('Review complete flag is not true. Incomplete reviews are rejected.');
  }

  return review;
}

/**
 * Builds the machine-readable run summary object.
 */
export function buildRunSummary({
  repo,
  pr,
  headSha,
  reviewerVersion = '0.1.0',
  model = 'deepseek/deepseek-v4.1-flash',
  modalMode = 'shared',
  modalSessionId,
  dockerSandboxId = null,
  timings = {},
  usage = null,
  result = 'success',
  findingsCount = 0,
  error = null,
}) {
  return {
    repo,
    pr: Number(pr),
    head_sha: headSha,
    reviewer_version: reviewerVersion,
    model,
    modal_mode: modalMode,
    modal_session_id: modalSessionId,
    docker_sandbox_id: dockerSandboxId,
    timings: {
      sandbox_start_seconds: timings.sandbox_start_seconds || 0,
      checkout_seconds: timings.checkout_seconds || 0,
      prepare_seconds: timings.prepare_seconds || 0,
      tool_smoke_seconds: timings.tool_smoke_seconds || 0,
      review_seconds: timings.review_seconds || 0,
      total_seconds: timings.total_seconds || 0,
    },
    usage: usage || {
      input_tokens: null,
      cached_input_tokens: null,
      output_tokens: null,
    },
    findings_count: findingsCount,
    result,
    error: error ? String(error) : null,
    timestamp: new Date().toISOString(),
  };
}

/**
 * Formats a verified review into GitHub PR comment markdown.
 */
export function formatReviewComment(review, { model, reviewerVersion = '0.1.0' } = {}) {
  const lines = [];

  lines.push(`## 🤖 Docker + Modal PR Reviewer`);
  lines.push(`**Model:** \`${model || 'deepseek/deepseek-v4.1-flash'}\` | **Reviewer:** \`v${reviewerVersion}\` | **Commit:** \`${review.head_sha.substring(0, 10)}\``);
  lines.push('');

  lines.push(`### Summary`);
  lines.push(review.summary);
  lines.push('');

  const findings = review.findings || [];
  if (findings.length === 0) {
    lines.push(`### Findings`);
    lines.push(`✅ **No actionable defects found in this change.**`);
    lines.push('');
  } else {
    lines.push(`### Findings (${findings.length})`);
    lines.push('');
    for (const f of findings) {
      const loc = f.path ? `\`${f.path}${f.line ? `:${f.line}` : ''}\`` : 'General';
      lines.push(`#### [${f.severity}] ${f.title}`);
      lines.push(`- **Location:** ${loc}`);
      lines.push(`- **Description:** ${f.description}`);
      if (f.evidence) {
        lines.push(`- **Evidence:**`);
        lines.push('```text');
        lines.push(f.evidence.trim());
        lines.push('```');
      }
      lines.push('');
    }
  }

  if (review.tests && review.tests.length > 0) {
    lines.push(`### Executed Checks`);
    for (const t of review.tests) {
      lines.push(`- \`${t.command}\`: ${t.result}`);
    }
    lines.push('');
  }

  if (review.limitations && review.limitations.length > 0) {
    lines.push(`### Limitations`);
    for (const l of review.limitations) {
      lines.push(`- ${l}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push(`*Generated by Docker Cloud Sandbox + Modal DeepSeek V4.1 Flash*`);

  return lines.join('\n');
}
